"""
Hermes Commands - Capa de comandos genérica para operaciones de escritura.

Principio: Los Commands NO saben de Telegram, WebSocket, HTTP, etc.
Reciben CompanyContext, UserContext y parámetros validados.
Devuelven CommandResult.

Separación clara: Query Layer (READ) ≠ Command Layer (WRITE)

COMMAND LAYER V1 ACTIVO (producción):
- thirdparty.create
- product.create
- service.create

EXPERIMENTAL / NO REGISTRADOS (require validation phase by phase):
- proposal.create
- invoice.create
- invoice.create_from_proposal
- supplier_invoice.create
- order.create
- supplier_order.create
- payment.create
- collection.create
- stock_movement.create
- project.create
- project.add_task
- bc3.import
- bc3.export
"""

from __future__ import annotations

from core.hermes.commands.base import CommandHandler, CommandRegistry, command_registry
from core.hermes.commands.models import (
    CommandIntent,
    CommandPreview,
    CommandResult,
    CommandStatus,
    CommandType,
    PendingCommand,
    ValidatedCommand,
)

# Import handlers to register them (only V1 active)
from .handlers import product, thirdparty  # noqa: F401

__all__ = [
    # Registry
    "CommandRegistry",
    "CommandHandler",
    "command_registry",
    "register_core_commands",
    # Models
    "CommandType",
    "CommandStatus",
    "CommandIntent",
    "CommandPreview",
    "PendingCommand",
    "ValidatedCommand",
    "CommandResult",
]


def register_core_commands() -> None:
    """Registrar handlers de comandos core en el registry global.

    Command Layer V1 activo:
    - thirdparty.create
    - product.create
    - service.create

    Supplier Invoice V3 (Gate E) - confirm-only handler:
    - supplier_invoice.create (ConfirmSupplierInvoiceHandler)
      NOTE: ConfirmSupplierInvoiceHandler is for EXECUTION (confirmation boundary) ONLY.
      Preview generation for supplier invoices uses ingestion service directly,
      so it does NOT implement generate_preview and is NOT registered in the command layer.

    El resto (proposal, invoice, order, payment, stock, project, bc3)
    quedan DESREGISTRADOS / EXPERIMENTAL hasta validación fase por fase.
    """
    from .handlers.product import CreateProductHandler, CreateServiceHandler
    from .handlers.thirdparty import CreateThirdpartyHandler

    command_registry.register_core_handler(CreateThirdpartyHandler())
    command_registry.register_core_handler(CreateProductHandler())
    command_registry.register_core_handler(CreateServiceHandler())

    # Supplier Invoice V3 - confirmation boundary (Gate E)
    # ConfirmSupplierInvoiceHandler is for EXECUTION only (no generate_preview).
    # Preview is generated by ingestion service directly in main.py.
    # command_registry.register_core_handler(ConfirmSupplierInvoiceHandler())

    # EXPERIMENTAL - NO REGISTRAR:
    # from .handlers.proposal import CreateProposalHandler
    # from .handlers.invoice import CreateInvoiceHandler, CreateInvoiceFromProposalHandler
    # from .handlers.supplier_invoice import CreateSupplierInvoiceHandler  # legacy V1
    # from .handlers.order import CreateOrderHandler, CreateSupplierOrderHandler
    # from .handlers.payment import CreatePaymentHandler, CreateCollectionHandler
    # from .handlers.stock_movement import CreateStockMovementHandler
    # from .handlers.project import CreateProjectHandler, AddProjectTaskHandler
    # from .handlers.bc3 import ImportBC3Handler, ExportBC3Handler
