#!/usr/bin/env bash
# scripts/configure/dolibarr.sh
# Configurar Dolibarr para una instancia específica
# Uso: ./scripts/configure/dolibarr.sh [INSTANCE=empresa_a]

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$(dirname "$SCRIPT_DIR")")"

INSTANCE="${INSTANCE:-${1:-}}"

if [[ -z "$INSTANCE" ]]; then
    echo "Uso: $0 INSTANCE=empresa_a"
    echo "   o: INSTANCE=empresa_a $0"
    exit 1
fi

# Colores
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

log_info()  { echo -e "${GREEN}[INFO]${NC} $*"; }
log_warn()  { echo -e "${YELLOW}[WARN]${NC} $*"; }
log_error() { echo -e "${RED}[ERROR]${NC} $*"; }
log_step()  { echo -e "${BLUE}[STEP]${NC} $*"; }

INSTANCE_DIR="${PROJECT_ROOT}/instances/${INSTANCE}"
CONFIG_YML="${INSTANCE_DIR}/config.yml"
INSTANCE_ENV="${INSTANCE_DIR}/instance.env"

if [[ ! -f "$CONFIG_YML" ]]; then
    log_error "Instancia ${INSTANCE} no encontrada"
    exit 1
fi

# Cargar variables de instance.env
if [[ -f "$INSTANCE_ENV" ]]; then
    set -a
    source "$INSTANCE_ENV"
    set +a
fi

# Extraer config de config.yml usando Python
eval $("${PROJECT_ROOT}/.venv/bin/python" -c "
import yaml, sys
with open('$CONFIG_YML') as f:
    cfg = yaml.safe_load(f)
db = cfg['database']
tg = cfg['telegram']
print(f'DB_NAME={db[\"db_name\"]}')
print(f'DB_USER={db[\"db_user\"]}')
print(f'DB_HOST={db[\"db_host\"]}')
print(f'DB_PORT={db[\"db_port\"]}')
print(f'DOLIBARR_INTERNAL_URL={db[\"internal_url\"]}')
print(f'DOLIBARR_DOCUMENTS={db[\"documents_path\"]}')
print(f'DOLIBARR_APACHE_PORT={cfg[\"dolibarr_apache_port\"]}')
print(f'TELEGRAM_WEBHOOK_PATH={tg[\"webhook_path\"]}')
")

log_step "Configurando Dolibarr para instancia ${INSTANCE}..."

# 1. Crear base de datos y usuario
log_info "Creando base de datos ${DB_NAME} y usuario ${DB_USER}..."
mysql -u root -p"${MARIADB_ROOT_PASSWORD}" << EOF
CREATE DATABASE IF NOT EXISTS \`${DB_NAME}\` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE USER IF NOT EXISTS '${DB_USER}'@'%' IDENTIFIED BY '${DOLIBARR_DB_PASSWORD}';
GRANT ALL PRIVILEGES ON \`${DB_NAME}\`.* TO '${DB_USER}'@'%';
FLUSH PRIVILEGES;
EOF

# 2. Crear directorio de documentos
log_info "Creando directorio de documentos: ${DOLIBARR_DOCUMENTS}"
mkdir -p "${DOLIBARR_DOCUMENTS}"
chown -R www-data:www-data "${DOLIBARR_DOCUMENTS}"
chmod 750 "${DOLIBARR_DOCUMENTS}"

# 3. Instalar/actualizar Dolibarr si no existe
DOLIBARR_HTDOCS="/var/www/dolibarr/${INSTANCE}/htdocs"
if [[ ! -f "${DOLIBARR_HTDOCS}/index.php" ]]; then
    log_info "Instalando Dolibarr en ${DOLIBARR_HTDOCS}..."
    mkdir -p "/var/www/dolibarr/${INSTANCE}"
    
    # Descargar Dolibarr si no está en el repo
    DOLIBARR_VERSION="23.0.4"
    if [[ ! -d "${PROJECT_ROOT}/dolibarr-${DOLIBARR_VERSION}" ]]; then
        log_warn "Dolibarr ${DOLIBARR_VERSION} no encontrado en ${PROJECT_ROOT}"
        log_info "Descargando..."
        cd /tmp
        wget -q "https://github.com/Dolibarr/dolibarr/archive/${DOLIBARR_VERSION}.tar.gz"
        tar -xzf "${DOLIBARR_VERSION}.tar.gz"
        mv "dolibarr-${DOLIBARR_VERSION}" "${PROJECT_ROOT}/dolibarr-${DOLIBARR_VERSION}"
    fi
    
    cp -r "${PROJECT_ROOT}/dolibarr-${DOLIBARR_VERSION}/htdocs" "/var/www/dolibarr/${INSTANCE}/"
    cp -r "${PROJECT_ROOT}/dolibarr-${DOLIBARR_VERSION}/scripts" "/var/www/dolibarr/${INSTANCE}/"
    
    # Permisos
    chown -R www-data:www-data "/var/www/dolibarr/${INSTANCE}"
    find "/var/www/dolibarr/${INSTANCE}/htdocs" -type f -exec chmod 640 {} \;
    find "/var/www/dolibarr/${INSTANCE}/htdocs" -type d -exec chmod 750 {} \;
fi

# 4. Generar conf.php
log_info "Generando conf.php..."
CONF_DIR="/var/www/dolibarr/${INSTANCE}/conf"
mkdir -p "${CONF_DIR}"

cat > "${CONF_DIR}/conf.php" << EOF
<?php
// Dolibarr configuration for ${INSTANCE}
// Generated by Gestor-IA - DO NOT EDIT MANUALLY

\$dolibarr_main_url_root = '${DOLIBARR_INTERNAL_URL}';
\$dolibarr_main_document_root = '/var/www/dolibarr/${INSTANCE}/htdocs';
\$dolibarr_main_data_root = '${DOLIBARR_DOCUMENTS}';

\$dolibarr_main_db_host = '${DB_HOST}';
\$dolibarr_main_db_port = '${DB_PORT}';
\$dolibarr_main_db_name = '${DB_NAME}';
\$dolibarr_main_db_user = '${DB_USER}';
\$dolibarr_main_db_pass = '${DOLIBARR_DB_PASSWORD}';
\$dolibarr_main_db_type = 'mysqli';

\$dolibarr_main_authentication = 'http';
\$dolibarr_main_session_name = 'DOLSESSID_${INSTANCE}';
\$dolibarr_main_cookie_domain = '';
\$dolibarr_main_cookie_path = '/';
\$dolibarr_main_cookie_secure = false;
\$dolibarr_main_cookie_httponly = true;

\$dolibarr_main_prod = 1;
\$dolibarr_main_demo = 0;
\$dolibarr_main_forced_encoding = 'UTF-8';
EOF

chown www-data:www-data "${CONF_DIR}/conf.php"
chmod 640 "${CONF_DIR}/conf.php"

# 5. Ejecutar instalador Dolibarr si es primera vez
if ! mysql -u "${DB_USER}" -p"${DOLIBARR_DB_PASSWORD}" "${DB_NAME}" -e "SELECT 1 FROM llx_const WHERE name='MAIN_INFO_SOCIETE_NOM' LIMIT 1;" 2>/dev/null; then
    log_info "Ejecutando instalador Dolibarr (primera vez)..."
    cd "/var/www/dolibarr/${INSTANCE}/htdocs/install"
    php install.php -f -q \
        --db_host="${DB_HOST}" \
        --db_port="${DB_PORT}" \
        --db_name="${DB_NAME}" \
        --db_user="${DB_USER}" \
        --db_pass="${DOLIBARR_DB_PASSWORD}" \
        --db_type="mysqli" \
        --admin_login="admin" \
        --admin_pass="$(openssl rand -base64 16)" \
        --lang="es_ES" \
        --country="ES" \
        --currency="EUR" \
        --timezone="Europe/Madrid" \
        --url_root="${DOLIBARR_INTERNAL_URL}/" \
        --data_root="${DOLIBARR_DOCUMENTS}"
    
    log_warn "Dolibarr instalado. Generar API Key en: ${DOLIBARR_INTERNAL_URL}/admin/apikey.php"
    log_warn "Actualizar DOLIBARR_API_KEY en ${INSTANCE_ENV}"
fi

# 6. Configurar Apache VirtualHost
log_info "Configurando Apache VirtualHost..."
bash "${SCRIPT_DIR}/apache.sh" "${INSTANCE}"

log_info "Dolibarr configurado para ${INSTANCE}"
log_info "URL interna: ${DOLIBARR_INTERNAL_URL}"
log_info "Directorio documentos: ${DOLIBARR_DOCUMENTS}"